# -*- coding: utf-8 -*-
"""dortislemarayuz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkRoW-Ys_K0s8hkbKbyMxh31JyPIkGfD
"""

!pip install gradio

import gradio as gr

def hesapla(sayi1, sayi2, islem):
    if islem == "Topla":
        return sayi1 + sayi2
    elif islem == "Çıkar":
        return sayi1 - sayi2
    elif islem == "Böl":
        return sayi1 / sayi2 if sayi2 != 0 else "Tanımsız"  # Bölme işlemi için sıfıra kontrol
    elif islem == "Çarp":
        return sayi1 * sayi2

# Arayüz oluşturma
with gr.Blocks() as demo:
    gr.Markdown("## Matematiksel İşlem Uygulaması")

    sayi1 = gr.Number(label="Birinci Sayı")
    sayi2 = gr.Number(label="İkinci Sayı")

    islem = gr.Dropdown(choices=["Topla", "Çıkar", "Böl", "Çarp"], label="İşlem Seçin")

    sonuc = gr.Textbox(label="Sonuç", interactive=False)

    hesapla_btn = gr.Button("Hesapla")

    hesapla_btn.click(hesapla, inputs=[sayi1, sayi2, islem], outputs=sonuc)

# Uygulamayı başlat
demo.launch()

